module RedisQueuedLocks
  module Acquirer
    module AcquireLock
      module DelayExecution
        def delay_execution: (Integer retry_delay, Integer retry_jitter) -> Integer
      end
    end
  end
end
