module RedisQueuedLocks
  module Acquirer
    module AcquireLock
      module DequeueFromLockQueue
        def dequeue_from_lock_queue: (
          ::RedisClient redis,
          ::Logger|::RedisQueuedLocks::_Loggable logger,
          ::String lock_key,
          ::String lock_key_queue,
          ::Integer queue_ttl,
          ::String acquier_id,
          ::String host_id,
          ::Symbol access_strategy,
          bool log_sampled,
          bool instr_sampled
        ) -> ::RedisQueuedLocks::Data
      end
    end
  end
end
