use RedisClient as RC

module RedisQueuedLocks
  module Acquirer
    module AcquireLock
      module WithAcqTimeout
        def with_acq_timeout: (
          RC::client redis,
          Integer? timeout,
          String lock_key,
          String lock_name,
          bool raise_errors,
          bool detailed_acq_timeout_error,
          ?on_timeout: Proc|nil
        ) { (?) -> untyped } -> untyped
      end
    end
  end
end
