use RedisClient as RC

module RedisQueuedLocks
  class Swarm
    module Acquirers
      type acquirersList = Hash[String,{ zombie: bool, last_probe_time: Time, last_probe_score: Float }]
      def self.acquirers: (RC::client redis_client, Integer zombie_ttl) -> acquirersList
    end
  end
end
