module RedisQueuedLocks
  class Swarm
    class ProbeHosts < SwarmElement::Threaded
      def self.probe_hosts: (
        ::RedisClient redis_client,
        ::String uniq_identity
      ) -> ::RedisQueuedLocks::Data

      def enabled?: () -> bool
      def spawn_main_loop!: () -> ::Thread
    end
  end
end
