use RedisClient as RC

module RedisQueuedLocks
  class Swarm
    module RedisClientBuilder
      def self.build: (
        ?pooled: bool,
        ?sentinel: bool,
        ?config: Hash[untyped,untyped],
        ?pool_config: Hash[untyped,untyped]
      ) -> RC::client

      private

      def self.sentinel_config: (Hash[Symbol,untyped] config) -> RC::SentinelConfig
      def self.non_sentinel_config: (Hash[Symbol,untyped] config) -> RC::Config
      def self.pooled_client: (RC::config redis_config, Hash[Symbol,untyped] pool_config) -> RedisClient::Pooled
      def self.non_pooled_client: (RC::config redis_config) -> RedisClient
    end
  end
end
