inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rake.yml
    - lib/rubocop.rspec.yml
    - lib/rubocop.rbs.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - sig/**/*.rbs
    - Gemfile
    - gemfiles/ruby3.3.gemfile
    - Rakefile
    - redis_queued_locks.gemspec
    - bin/console

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/**/*.rb

Gemspec/DevelopmentDependencies:
  EnforcedStyle: Gemfile

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false
