module RedisQueuedLocks
  module Acquier
    module AcquireLock
      module DequeueFromLockQueue
        module LogVisitor
          def self.dequeue_from_lock_queue: (
            ::Logger|RedisQueuedLocks::_Loggable logger,
            bool log_sampled,
            ::String lock_key,
            ::Integer queue_ttl,
            ::String acquier_id,
            ::String host_id,
            ::Symbol access_strategy
          ) -> void
        end
      end
    end
  end
end
