module RedisQueuedLocks
  module Acquier
    module LockInfo
      def self.lock_info: (
        ::RedisClient redis_client,
        ::String lock_name
      ) -> ::Hash[::String,::String|::Float|::Integer]?
    end
  end
end
