module RedisQueuedLocks
  module Acquier
    module QueueInfo
      def self.queue_info: (
        ::RedisClient redis_client,
        ::String lock_name
      ) -> { "lock_queue" => ::String, "queue" => ::Array[{ "acq_id" => ::String, "score" => ::Integer|::Float}] }?
    end
  end
end
