module RedisQueuedLocks
  interface _Loggable
    def debug: (?untyped? progname) { (?) -> untyped } -> untyped
  end

  interface _Instrumentable
    def notify: (String event, ?Hash[untyped,untyped] payload) -> void
  end

  type loggerObj = Object & _Loggable
  type instrObj = Object & _Instrumentable

  extend ::RedisQueuedLocks::Debugger::Interface
end
