use RedisQueuedLocks as RQL
use RedisClient as RC

module RedisQueuedLocks
  module Acquirer
    module ExtendLockTTL
      EXTEND_LOCK_PTTL: String

      type extendResult = { ok: bool, result: { extended_locks_count: Integer } | Symbol }
      def self.extend_lock_ttl: (
        RC::client redis_client,
        String lock_name,
        Integer milliseconds,
        Symbol read_write_mode,
        bool all_read_locks,
        String acquirer_id,
        RQL::loggerObj logger,
        RQL::instrObj instrumenter,
        untyped? instrument,
        bool log_samling_enabled,
        Integer log_sampling_percent,
        RQL::Logging::samplerObj log_sampler,
        bool sample_this,
        bool instr_sampling_enabled,
        Integer instr_sampling_percent,
        RQL::Instrument::samplerObj instr_sampler,
        bool instr_sample_this
      ) -> extendResult

      private def self.extend_read_lock_ttl: (
        RC::client redis_client,
        String lock_name,
        String lock_key,
        String acquirer_id,
        Integer milliseconds
      ) -> extendResult

      private def self.extend_all_read_locks_ttl: (
        RC::client redis_client,
        String lock_name,
        String lock_key,
        Integer milliseconds
      ) -> extendResult
    end
  end
end
