use RedisClient as RC

module RedisQueuedLocks
  module Acquirer
    module Keys
      type keyList = Set[String]
      def self.keys: (RC::client redis_client, scan_size: Integer) -> keyList
    end
  end
end
