use RedisClient as RC

module RedisQueuedLocks
  module Acquirer
    module Locks
      type lockList = Set[String]
      type locksInfo = Set[{ lock: String, status: Symbol, info: Hash[String,String|Float|Integer] }]
      type locks = lockList | locksInfo

      def self.locks: (RC::client redis_client, scan_size: Integer, with_info: bool) -> locks

      private def self.scan_locks: (RC::client redis_client, Integer scan_size) -> lockList
      private def self.extract_locks_info: (RC::client redis_client, Set[::String] lock_keys) -> locksInfo
    end
  end
end
