use RedisClient as RC

module RedisQueuedLocks
  module Acquirer
    module LockInfo
      type lockInfo = Hash[String,String|Float|Integer]
      def self.lock_info: (RC::client redis_client, String lock_name) -> lockInfo?
    end
  end
end
