use RedisClient as RC

module RedisQueuedLocks
  module Acquirer
    module Locks
      type readerInfo = Hash[String,String|Float|Integer|nil]
      type lockInfo = Hash[String,String|Float|Integer|Array[readerInfo]]
      type lockList = Set[String]
      type locksInfo = Set[{ lock: String, status: Symbol, info: lockInfo }]
      type locks = lockList | locksInfo

      def self.locks: (RC::client redis_client, scan_size: Integer, with_info: bool) -> locks

      private def self.scan_locks: (RC::client redis_client, Integer scan_size) -> lockList
      private def self.extract_locks_info: (RC::client redis_client, Set[::String] lock_keys) -> locksInfo
      private def self.read_lock_info: (
        RC::client redis_client,
        String lock_name,
        String lock_key,
        Array[String] redis_time,
        Array[[String, Float]] read_locks
      ) -> lockInfo?
    end
  end
end
