use RedisClient as RC

module RedisQueuedLocks
  module Acquirer
    module QueueInfo
      type queueRequest = Hash[String,String|Integer|Float]
      type queueInfo = Hash[String,String|Array[queueRequest]]
      def self.queue_info: (RC::client redis_client, String lock_name) -> queueInfo?
    end
  end
end
