use RedisQueuedLocks as RQL
use RedisClient as RC

module RedisQueuedLocks
  module Acquirer
    module ReleaseReadLock
      extend RQL::Utilities

      type releaseResult = {
        ok: bool,
        result: {
          rel_time: Integer|Float,
          rel_key: String,
          rel_acq_id: String,
          lock_res: Symbol
        }
      }
      def self.release_read_lock: (
        RC::client redis,
        String lock_name,
        String acquirer_id,
        RQL::instrObj instrumenter,
        RQL::loggerObj logger,
        untyped? instrument,
        bool log_sampling_enabled,
        Integer log_sampling_percent,
        RQL::Logging::samplerObj log_sampler,
        bool log_sample_this,
        bool instr_sampling_enabled,
        Integer instr_sampling_percent,
        RQL::Instrument::samplerObj instr_sampler,
        bool instr_sample_this
      ) -> releaseResult

      type fullReleaseResult = { ok: bool, result: { lock: Symbol } }
      private def self.fully_release_read_lock: (
        RC::client redis,
        String lock_readers_key,
        String read_lock_key,
        String acquirer_id
      ) -> fullReleaseResult
    end
  end
end
