use RedisClient as RC
use RedisQueuedLocks as RQL

module RedisQueuedLocks
  module Acquirer
    module ReleaseLocksOf
      extend RQL::Utilities

      type removeResult = untyped
      def self.release_locks_of: (
        RC::client redis,
        ?String acquirer_id,
        ?String host_id,
        Integer scan_size,
        RQL::loggerObj logger,
        RQL::instrObj instrumenter,
        untyped instrument,
        bool log_sampling_enabled,
        Integer log_sampling_percent,
        RQL::Logging::samplerObj log_sampler,
        bool log_sample_this,
        bool instr_sampling_enabled,
        Integer instr_sampling_percent,
        RQL::Instrument::samplerObj instr_sampler,
        bool instr_sample_this
      ) -> removeResult
    end
  end
end
