module RedisQueuedLocks
  class Error < ::StandardError
  end

  class ArgumentError < ::ArgumentError
  end

  class LockAlreadyObtainedError < Error
  end

  class LockAcquirementIntermediateTimeoutError < ::Timeout::Error
  end

  class LockAcquirementTimeoutError < Error
  end

  class LockAcquirementRetryLimitError < Error
  end

  class TimedLockIntermediateTimeoutError < ::Timeout::Error
  end

  class TimedLockTimeoutError < Error
  end

  class ConflictLockObtainError < Error
  end

  class SwarmError < Error
  end

  class SwarmArgumentError < ArgumentError
  end
end
