use RedisQueuedLocks as RQL

module RedisQueuedLocks
  module Instrument
    interface _Sampler
      def sampling_happened?: (Integer sampling_percent) -> bool
    end

    type samplerObj = Object & _Sampler

    def self.should_instrument?: (bool instr_sampling_enabled, bool instr_sample_this, Integer instr_sampling_percent, samplerObj instr_sampler) -> bool
    def self.valid_sampler?: (untyped sampler) -> bool
    def self.valid_interface?: (untyped instrumenter) -> bool
  end
end
