use RedisQueuedLocks as RQL

module RedisQueuedLocks
  class Swarm
    module SwarmElement
      class Isolated
        include RQL::Utilities

        @rql_client: RQL::Client
        @swarm_element: Ractor?
        @sync: RQL::Utilities::Lock

        attr_reader rql_client: RQL::Client
        attr_reader swarm_element: Ractor?
        attr_reader sync: RQL::Utilities::Lock

        def initialize: (RQL::Client rql_client) -> void
        def try_swarm!: () -> void
        def reswarm_if_dead!: () -> void
        def try_kill!: () -> void
        def enabled?: () -> bool

        type elementStatus = {
          enabled: bool,
          ractor: { running: bool, state: String },
          main_loop: { running: bool, status: String }
        }
        def status: () -> elementStatus

        def self.swarm_loop: () { () -> Thread } -> void

        private

        def swarm!: () -> void
        def idle?: () -> bool
        def swarmed?: () -> bool
        def swarmed__alive?: () -> bool
        def swarmed__dead?: () -> bool
        def swarmed__running?: () -> bool
        def swarmed__stopped?: () -> bool
        def swarm_loop__is_active: () -> bool

        type swarmLoopStatus = { main_loop: { alive: bool, state: String } }
        def swarm_loop__status: () -> swarmLoopStatus?

        def swarm_loop__start: () -> void
        def swarm_loop__pause: () -> void
        def swarm_loop__kill: () -> void
      end
    end
  end
end
