name: Build (Linter + Specs)
on: [push, pull_request]
jobs:
  linst-and-test:
    runs-on: ubuntu-latest
    matrix:
      ruby_version: ["3.1", "3.2", "3.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: supercharge/redis-github-action@1.7.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Linter
        run: bundle exec rake rubocop
      - name: Specs
        run: bundle exec rake rspec
